nav:
  Home: /
  About: /about/
  Writing: /archives/
  tags: /tags/
  categories: /categories/
  Search: /Search/

projects_url: https://github.com/PorcoRosso000

customize:
    gravatar: 
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/PorcoRosso000
    #显示全部贴子
    show_all_posts: false
    #仅显示几张贴子
    post_count: 5
    highlight: agate

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
        
#在  Writing中展示所有文章      
archive_generator:
  per_page: 0 # 设置为 0 显示所有文章
  yearly: true
  monthly: true
  daily: false




  
